#!/usr/bin/env python3
import argparse
from pathlib import Path


NODE_DEPS_ROOTS = (
    "undici",
    "acorn",
    "minimatch",
    "cjs-module-lexer",
    "amaro",
    "v8/tools",
)


def strip_ext(path: Path) -> str:
    text = path.as_posix()
    if text.endswith(".js"):
        return text[:-3]
    if text.endswith(".mjs"):
        return text[:-4]
    return text


def collect_ids(node_lib_root: Path, node_deps_root: Path) -> list[str]:
    ids: set[str] = set()

    if node_lib_root.is_dir():
        for path in node_lib_root.rglob("*.js"):
            ids.add(strip_ext(path.relative_to(node_lib_root)))

    if node_deps_root.is_dir():
        for dep_root in NODE_DEPS_ROOTS:
            root = node_deps_root / dep_root
            if not root.exists():
                continue
            for path in root.rglob("*"):
                if path.suffix not in (".js", ".mjs") or not path.is_file():
                    continue
                dep_id = strip_ext(path.relative_to(node_deps_root))
                ids.add(f"internal/deps/{dep_id}")

    return sorted(ids)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--node-lib-root", required=True)
    parser.add_argument("--node-deps-root", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    builtin_ids = collect_ids(Path(args.node_lib_root), Path(args.node_deps_root))
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)

    with out.open("w", encoding="utf-8") as f:
        f.write("// Generated by ubi/cmake/generate_builtin_ids.py\n")
        f.write("static const char* const kGeneratedBuiltinIds[] = {\n")
        for builtin_id in builtin_ids:
            f.write(f'    "{builtin_id}",\n')
        f.write("};\n")


if __name__ == "__main__":
    main()
