#ifndef SRC_UBI_VERSION_H_
#define SRC_UBI_VERSION_H_

#define UBI_MAJOR_VERSION 0
#define UBI_MINOR_VERSION 0
#define UBI_PATCH_VERSION 0

#ifndef UBI_STRINGIFY
#define UBI_STRINGIFY(n) UBI_STRINGIFY_HELPER(n)
#define UBI_STRINGIFY_HELPER(n) #n
#endif

#define UBI_VERSION_STRING UBI_STRINGIFY(UBI_MAJOR_VERSION) "." \
                           UBI_STRINGIFY(UBI_MINOR_VERSION) "." \
                           UBI_STRINGIFY(UBI_PATCH_VERSION)
#define UBI_VERSION "v" UBI_VERSION_STRING

#endif  // SRC_UBI_VERSION_H_
